name: CI
on: [push]
jobs:
  main:
    name: npm test
    runs-on: ubuntu-22.04	
    strategy:
      matrix:
        version:
          - 16
          - 17
          - 18
    steps:
    - uses: zendesk/checkout@v3
    - uses: zendesk/setup-node@v3
      with:
        node-version: ${{ matrix.version }}
    - name: install
      run: |
        sudo apt update
        sudo apt install -y redis-server
        npm install
    - name: node_js ${{ matrix.version }}
      run: |
        redis-server --version
        verbose=1 npm test
